theme: minima
title: I Love Meat and Booze!
author: StewieLil
email: stewielil22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  As the title suggest this is a site solely dedicated to expressing how much I love meat and booze. 
  Steak, chicken, pork, whiskey, beer, and whatever else that gets me drunk and full.
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
